name: Hola Mundo con JavaScript

on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
    
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Ejecutar Hola Mundo
        run: node hola-mundo.js
