name: Aprendiendo GitHub Actions
run-name: Github ACT
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Correr script
        run: test0.js
